import dayjs from "dayjs";
import { PropertyData } from "../PropertyDataContext";

const data = {
  subsidy: 0,
  finalYear: 7,
  isHousing: false,
  discharges: [
    {
      type: "Mensal",
      month: 1,
      value: 5000,
      indexType: "CUB",
      indexValue: "1",
      initialMonth: 1,
      isDownPayment: false,
      originalValue: 5000,
      isInstallmentPlan: true,
      isConstructionInterest: false,
    },
    {
      type: "Mensal",
      month: 2,
      value: 5050,
      indexType: "CUB",
      indexValue: "1",
      initialMonth: 1,
      isDownPayment: false,
      originalValue: 5000,
      isInstallmentPlan: true,
      isConstructionInterest: false,
    },
    {
      type: "Mensal",
      month: 3,
      value: 5100.5,
      indexType: "CUB",
      indexValue: "1",
      initialMonth: 1,
      isDownPayment: false,
      originalValue: 5000,
      isInstallmentPlan: true,
      isConstructionInterest: false,
    },
    {
      type: "Mensal",
      month: 4,
      value: 5151.505000000001,
      indexType: "CUB",
      indexValue: "1",
      initialMonth: 1,
      isDownPayment: false,
      originalValue: 5000,
      isInstallmentPlan: true,
      isConstructionInterest: false,
    },
    {
      type: "Mensal",
      month: 5,
      value: 5203.02005,
      indexType: "CUB",
      indexValue: "1",
      initialMonth: 1,
      isDownPayment: false,
      originalValue: 5000,
      isInstallmentPlan: true,
      isConstructionInterest: false,
    },
    {
      type: "Mensal",
      month: 6,
      value: 5255.0502505,
      indexType: "CUB",
      indexValue: "1",
      initialMonth: 1,
      isDownPayment: false,
      originalValue: 5000,
      isInstallmentPlan: true,
      isConstructionInterest: false,
    },
    {
      type: "Mensal",
      month: 7,
      value: 5307.600753005001,
      indexType: "CUB",
      indexValue: "1",
      initialMonth: 1,
      isDownPayment: false,
      originalValue: 5000,
      isInstallmentPlan: true,
      isConstructionInterest: false,
    },
    {
      type: "Mensal",
      month: 8,
      value: 5360.676760535051,
      indexType: "CUB",
      indexValue: "1",
      initialMonth: 1,
      isDownPayment: false,
      originalValue: 5000,
      isInstallmentPlan: true,
      isConstructionInterest: false,
    },
    {
      type: "Mensal",
      month: 9,
      value: 5414.283528140401,
      indexType: "CUB",
      indexValue: "1",
      initialMonth: 1,
      isDownPayment: false,
      originalValue: 5000,
      isInstallmentPlan: true,
      isConstructionInterest: false,
    },
    {
      type: "Mensal",
      month: 10,
      value: 5468.426363421804,
      indexType: "CUB",
      indexValue: "1",
      initialMonth: 1,
      isDownPayment: false,
      originalValue: 5000,
      isInstallmentPlan: true,
      isConstructionInterest: false,
    },
    {
      type: "Mensal",
      month: 11,
      value: 5523.110627056023,
      indexType: "CUB",
      indexValue: "1",
      initialMonth: 1,
      isDownPayment: false,
      originalValue: 5000,
      isInstallmentPlan: true,
      isConstructionInterest: false,
    },
    {
      type: "Mensal",
      month: 12,
      value: 5578.341733326582,
      indexType: "CUB",
      indexValue: "1",
      initialMonth: 1,
      isDownPayment: false,
      originalValue: 5000,
      isInstallmentPlan: true,
      isConstructionInterest: false,
    },
    {
      type: "Mensal",
      month: 13,
      value: 5634.125150659849,
      indexType: "CUB",
      indexValue: "1",
      initialMonth: 1,
      isDownPayment: false,
      originalValue: 5000,
      isInstallmentPlan: true,
      isConstructionInterest: false,
    },
    {
      type: "Mensal",
      month: 14,
      value: 5690.466402166448,
      indexType: "CUB",
      indexValue: "1",
      initialMonth: 1,
      isDownPayment: false,
      originalValue: 5000,
      isInstallmentPlan: true,
      isConstructionInterest: false,
    },
    {
      type: "Mensal",
      month: 15,
      value: 5747.371066188113,
      indexType: "CUB",
      indexValue: "1",
      initialMonth: 1,
      isDownPayment: false,
      originalValue: 5000,
      isInstallmentPlan: true,
      isConstructionInterest: false,
    },
    {
      type: "Mensal",
      month: 16,
      value: 5804.844776849994,
      indexType: "CUB",
      indexValue: "1",
      initialMonth: 1,
      isDownPayment: false,
      originalValue: 5000,
      isInstallmentPlan: true,
      isConstructionInterest: false,
    },
    {
      type: "Mensal",
      month: 17,
      value: 5862.893224618494,
      indexType: "CUB",
      indexValue: "1",
      initialMonth: 1,
      isDownPayment: false,
      originalValue: 5000,
      isInstallmentPlan: true,
      isConstructionInterest: false,
    },
    {
      type: "Mensal",
      month: 18,
      value: 5921.522156864678,
      indexType: "CUB",
      indexValue: "1",
      initialMonth: 1,
      isDownPayment: false,
      originalValue: 5000,
      isInstallmentPlan: true,
      isConstructionInterest: false,
    },
    {
      type: "Mensal",
      month: 19,
      value: 5980.737378433325,
      indexType: "CUB",
      indexValue: "1",
      initialMonth: 1,
      isDownPayment: false,
      originalValue: 5000,
      isInstallmentPlan: true,
      isConstructionInterest: false,
    },
    {
      type: "Mensal",
      month: 20,
      value: 6040.544752217658,
      indexType: "CUB",
      indexValue: "1",
      initialMonth: 1,
      isDownPayment: false,
      originalValue: 5000,
      isInstallmentPlan: true,
      isConstructionInterest: false,
    },
    {
      type: "Mensal",
      month: 21,
      value: 6100.950199739836,
      indexType: "CUB",
      indexValue: "1",
      initialMonth: 1,
      isDownPayment: false,
      originalValue: 5000,
      isInstallmentPlan: true,
      isConstructionInterest: false,
    },
    {
      type: "Mensal",
      month: 22,
      value: 6161.959701737234,
      indexType: "CUB",
      indexValue: "1",
      initialMonth: 1,
      isDownPayment: false,
      originalValue: 5000,
      isInstallmentPlan: true,
      isConstructionInterest: false,
    },
    {
      type: "Mensal",
      month: 23,
      value: 6223.579298754606,
      indexType: "CUB",
      indexValue: "1",
      initialMonth: 1,
      isDownPayment: false,
      originalValue: 5000,
      isInstallmentPlan: true,
      isConstructionInterest: false,
    },
    {
      type: "Mensal",
      month: 24,
      value: 6285.815091742152,
      indexType: "CUB",
      indexValue: "1",
      initialMonth: 1,
      isDownPayment: false,
      originalValue: 5000,
      isInstallmentPlan: true,
      isConstructionInterest: false,
    },
    {
      type: "Mensal",
      month: 25,
      value: 6348.673242659574,
      indexType: "CUB",
      indexValue: "1",
      initialMonth: 1,
      isDownPayment: false,
      originalValue: 5000,
      isInstallmentPlan: true,
      isConstructionInterest: false,
    },
    {
      type: "Mensal",
      month: 26,
      value: 6412.159975086169,
      indexType: "CUB",
      indexValue: "1",
      initialMonth: 1,
      isDownPayment: false,
      originalValue: 5000,
      isInstallmentPlan: true,
      isConstructionInterest: false,
    },
    {
      type: "Mensal",
      month: 27,
      value: 6476.281574837031,
      indexType: "CUB",
      indexValue: "1",
      initialMonth: 1,
      isDownPayment: false,
      originalValue: 5000,
      isInstallmentPlan: true,
      isConstructionInterest: false,
    },
    {
      type: "Mensal",
      month: 28,
      value: 6541.044390585402,
      indexType: "CUB",
      indexValue: "1",
      initialMonth: 1,
      isDownPayment: false,
      originalValue: 5000,
      isInstallmentPlan: true,
      isConstructionInterest: false,
    },
    {
      type: "Mensal",
      month: 29,
      value: 6606.454834491255,
      indexType: "CUB",
      indexValue: "1",
      initialMonth: 1,
      isDownPayment: false,
      originalValue: 5000,
      isInstallmentPlan: true,
      isConstructionInterest: false,
    },
    {
      type: "Mensal",
      month: 30,
      value: 6672.519382836168,
      indexType: "CUB",
      indexValue: "1",
      initialMonth: 1,
      isDownPayment: false,
      originalValue: 5000,
      isInstallmentPlan: true,
      isConstructionInterest: false,
    },
    {
      type: "Mensal",
      month: 31,
      value: 6739.244576664531,
      indexType: "CUB",
      indexValue: "1",
      initialMonth: 1,
      isDownPayment: false,
      originalValue: 5000,
      isInstallmentPlan: true,
      isConstructionInterest: false,
    },
    {
      type: "Mensal",
      month: 32,
      value: 6806.637022431176,
      indexType: "CUB",
      indexValue: "1",
      initialMonth: 1,
      isDownPayment: false,
      originalValue: 5000,
      isInstallmentPlan: true,
      isConstructionInterest: false,
    },
    {
      type: "Mensal",
      month: 33,
      value: 6874.703392655487,
      indexType: "CUB",
      indexValue: "1",
      initialMonth: 1,
      isDownPayment: false,
      originalValue: 5000,
      isInstallmentPlan: true,
      isConstructionInterest: false,
    },
    {
      type: "Mensal",
      month: 34,
      value: 6943.450426582041,
      indexType: "CUB",
      indexValue: "1",
      initialMonth: 1,
      isDownPayment: false,
      originalValue: 5000,
      isInstallmentPlan: true,
      isConstructionInterest: false,
    },
    {
      type: "Mensal",
      month: 35,
      value: 7012.884930847862,
      indexType: "CUB",
      indexValue: "1",
      initialMonth: 1,
      isDownPayment: false,
      originalValue: 5000,
      isInstallmentPlan: true,
      isConstructionInterest: false,
    },
    {
      type: "Mensal",
      month: 36,
      value: 7083.013780156341,
      indexType: "CUB",
      indexValue: "1",
      initialMonth: 1,
      isDownPayment: false,
      originalValue: 5000,
      isInstallmentPlan: true,
      isConstructionInterest: false,
    },
    {
      type: "Mensal",
      month: 37,
      value: 7153.843917957905,
      indexType: "CUB",
      indexValue: "1",
      initialMonth: 1,
      isDownPayment: false,
      originalValue: 5000,
      isInstallmentPlan: true,
      isConstructionInterest: false,
    },
    {
      type: "Mensal",
      month: 38,
      value: 7225.382357137484,
      indexType: "CUB",
      indexValue: "1",
      initialMonth: 1,
      isDownPayment: false,
      originalValue: 5000,
      isInstallmentPlan: true,
      isConstructionInterest: false,
    },
    {
      type: "Mensal",
      month: 39,
      value: 7297.636180708859,
      indexType: "CUB",
      indexValue: "1",
      initialMonth: 1,
      isDownPayment: false,
      originalValue: 5000,
      isInstallmentPlan: true,
      isConstructionInterest: false,
    },
    {
      type: "Mensal",
      month: 40,
      value: 7370.612542515947,
      indexType: "CUB",
      indexValue: "1",
      initialMonth: 1,
      isDownPayment: false,
      originalValue: 5000,
      isInstallmentPlan: true,
      isConstructionInterest: false,
    },
    {
      type: "Mensal",
      month: 41,
      value: 7444.318667941106,
      indexType: "CUB",
      indexValue: "1",
      initialMonth: 1,
      isDownPayment: false,
      originalValue: 5000,
      isInstallmentPlan: true,
      isConstructionInterest: false,
    },
    {
      type: "Mensal",
      month: 42,
      value: 7518.761854620519,
      indexType: "CUB",
      indexValue: "1",
      initialMonth: 1,
      isDownPayment: false,
      originalValue: 5000,
      isInstallmentPlan: true,
      isConstructionInterest: false,
    },
    {
      type: "Mensal",
      month: 43,
      value: 7593.949473166724,
      indexType: "CUB",
      indexValue: "1",
      initialMonth: 1,
      isDownPayment: false,
      originalValue: 5000,
      isInstallmentPlan: true,
      isConstructionInterest: false,
    },
    {
      type: "Mensal",
      month: 44,
      value: 7669.888967898391,
      indexType: "CUB",
      indexValue: "1",
      initialMonth: 1,
      isDownPayment: false,
      originalValue: 5000,
      isInstallmentPlan: true,
      isConstructionInterest: false,
    },
    {
      type: "Mensal",
      month: 45,
      value: 7746.587857577375,
      indexType: "CUB",
      indexValue: "1",
      initialMonth: 1,
      isDownPayment: false,
      originalValue: 5000,
      isInstallmentPlan: true,
      isConstructionInterest: false,
    },
    {
      type: "Mensal",
      month: 46,
      value: 7824.053736153148,
      indexType: "CUB",
      indexValue: "1",
      initialMonth: 1,
      isDownPayment: false,
      originalValue: 5000,
      isInstallmentPlan: true,
      isConstructionInterest: false,
    },
    {
      type: "Mensal",
      month: 47,
      value: 7902.29427351468,
      indexType: "CUB",
      indexValue: "1",
      initialMonth: 1,
      isDownPayment: false,
      originalValue: 5000,
      isInstallmentPlan: true,
      isConstructionInterest: false,
    },
    {
      type: "Mensal",
      month: 48,
      value: 7981.317216249827,
      indexType: "CUB",
      indexValue: "1",
      initialMonth: 1,
      isDownPayment: false,
      originalValue: 5000,
      isInstallmentPlan: true,
      isConstructionInterest: false,
    },
    {
      type: "Mensal",
      month: 49,
      value: 8061.130388412325,
      indexType: "CUB",
      indexValue: "1",
      initialMonth: 1,
      isDownPayment: false,
      originalValue: 5000,
      isInstallmentPlan: true,
      isConstructionInterest: false,
    },
    {
      type: "Mensal",
      month: 50,
      value: 8141.741692296448,
      indexType: "CUB",
      indexValue: "1",
      initialMonth: 1,
      isDownPayment: false,
      originalValue: 5000,
      isInstallmentPlan: true,
      isConstructionInterest: false,
    },
    {
      type: "Mensal",
      month: 51,
      value: 8223.159109219414,
      indexType: "CUB",
      indexValue: "1",
      initialMonth: 1,
      isDownPayment: false,
      originalValue: 5000,
      isInstallmentPlan: true,
      isConstructionInterest: false,
    },
    {
      type: "Mensal",
      month: 52,
      value: 8305.390700311607,
      indexType: "CUB",
      indexValue: "1",
      initialMonth: 1,
      isDownPayment: false,
      originalValue: 5000,
      isInstallmentPlan: true,
      isConstructionInterest: false,
    },
    {
      type: "Mensal",
      month: 53,
      value: 8388.444607314723,
      indexType: "CUB",
      indexValue: "1",
      initialMonth: 1,
      isDownPayment: false,
      originalValue: 5000,
      isInstallmentPlan: true,
      isConstructionInterest: false,
    },
    {
      type: "Mensal",
      month: 54,
      value: 8472.32905338787,
      indexType: "CUB",
      indexValue: "1",
      initialMonth: 1,
      isDownPayment: false,
      originalValue: 5000,
      isInstallmentPlan: true,
      isConstructionInterest: false,
    },
    {
      type: "Mensal",
      month: 55,
      value: 8557.052343921749,
      indexType: "CUB",
      indexValue: "1",
      initialMonth: 1,
      isDownPayment: false,
      originalValue: 5000,
      isInstallmentPlan: true,
      isConstructionInterest: false,
    },
    {
      type: "Mensal",
      month: 56,
      value: 8642.622867360968,
      indexType: "CUB",
      indexValue: "1",
      initialMonth: 1,
      isDownPayment: false,
      originalValue: 5000,
      isInstallmentPlan: true,
      isConstructionInterest: false,
    },
    {
      type: "Mensal",
      month: 57,
      value: 8729.049096034576,
      indexType: "CUB",
      indexValue: "1",
      initialMonth: 1,
      isDownPayment: false,
      originalValue: 5000,
      isInstallmentPlan: true,
      isConstructionInterest: false,
    },
    {
      type: "Mensal",
      month: 58,
      value: 8816.339586994922,
      indexType: "CUB",
      indexValue: "1",
      initialMonth: 1,
      isDownPayment: false,
      originalValue: 5000,
      isInstallmentPlan: true,
      isConstructionInterest: false,
    },
    {
      type: "Mensal",
      month: 59,
      value: 8904.502982864873,
      indexType: "CUB",
      indexValue: "1",
      initialMonth: 1,
      isDownPayment: false,
      originalValue: 5000,
      isInstallmentPlan: true,
      isConstructionInterest: false,
    },
    {
      type: "Mensal",
      month: 60,
      value: 8993.54801269352,
      indexType: "CUB",
      indexValue: "1",
      initialMonth: 1,
      isDownPayment: false,
      originalValue: 5000,
      isInstallmentPlan: true,
      isConstructionInterest: false,
    },
    {
      type: "Mensal",
      month: 61,
      value: 9083.483492820456,
      indexType: "CUB",
      indexValue: "1",
      initialMonth: 1,
      isDownPayment: false,
      originalValue: 5000,
      isInstallmentPlan: true,
      isConstructionInterest: false,
    },
    {
      type: "Mensal",
      month: 62,
      value: 9174.31832774866,
      indexType: "CUB",
      indexValue: "1",
      initialMonth: 1,
      isDownPayment: false,
      originalValue: 5000,
      isInstallmentPlan: true,
      isConstructionInterest: false,
    },
    {
      type: "Mensal",
      month: 63,
      value: 9266.061511026148,
      indexType: "CUB",
      indexValue: "1",
      initialMonth: 1,
      isDownPayment: false,
      originalValue: 5000,
      isInstallmentPlan: true,
      isConstructionInterest: false,
    },
    {
      type: "Mensal",
      month: 64,
      value: 9358.72212613641,
      indexType: "CUB",
      indexValue: "1",
      initialMonth: 1,
      isDownPayment: false,
      originalValue: 5000,
      isInstallmentPlan: true,
      isConstructionInterest: false,
    },
    {
      type: "Mensal",
      month: 65,
      value: 9452.309347397773,
      indexType: "CUB",
      indexValue: "1",
      initialMonth: 1,
      isDownPayment: false,
      originalValue: 5000,
      isInstallmentPlan: true,
      isConstructionInterest: false,
    },
    {
      type: "Mensal",
      month: 66,
      value: 9546.83244087175,
      indexType: "CUB",
      indexValue: "1",
      initialMonth: 1,
      isDownPayment: false,
      originalValue: 5000,
      isInstallmentPlan: true,
      isConstructionInterest: false,
    },
    {
      type: "Mensal",
      month: 67,
      value: 9642.300765280468,
      indexType: "CUB",
      indexValue: "1",
      initialMonth: 1,
      isDownPayment: false,
      originalValue: 5000,
      isInstallmentPlan: true,
      isConstructionInterest: false,
    },
    {
      type: "Mensal",
      month: 68,
      value: 9738.723772933274,
      indexType: "CUB",
      indexValue: "1",
      initialMonth: 1,
      isDownPayment: false,
      originalValue: 5000,
      isInstallmentPlan: true,
      isConstructionInterest: false,
    },
    {
      type: "Mensal",
      month: 69,
      value: 9836.111010662606,
      indexType: "CUB",
      indexValue: "1",
      initialMonth: 1,
      isDownPayment: false,
      originalValue: 5000,
      isInstallmentPlan: true,
      isConstructionInterest: false,
    },
    {
      type: "Mensal",
      month: 70,
      value: 9934.472120769233,
      indexType: "CUB",
      indexValue: "1",
      initialMonth: 1,
      isDownPayment: false,
      originalValue: 5000,
      isInstallmentPlan: true,
      isConstructionInterest: false,
    },
    {
      type: "Mensal",
      month: 71,
      value: 10033.81684197693,
      indexType: "CUB",
      indexValue: "1",
      initialMonth: 1,
      isDownPayment: false,
      originalValue: 5000,
      isInstallmentPlan: true,
      isConstructionInterest: false,
    },
    {
      type: "Mensal",
      month: 72,
      value: 10134.15501039669,
      indexType: "CUB",
      indexValue: "1",
      initialMonth: 1,
      isDownPayment: false,
      originalValue: 5000,
      isInstallmentPlan: true,
      isConstructionInterest: false,
    },
    {
      type: "Mensal",
      month: 73,
      value: 10235.49656050066,
      indexType: "CUB",
      indexValue: "1",
      initialMonth: 1,
      isDownPayment: false,
      originalValue: 5000,
      isInstallmentPlan: true,
      isConstructionInterest: false,
    },
    {
      type: "Mensal",
      month: 74,
      value: 10337.85152610567,
      indexType: "CUB",
      indexValue: "1",
      initialMonth: 1,
      isDownPayment: false,
      originalValue: 5000,
      isInstallmentPlan: true,
      isConstructionInterest: false,
    },
    {
      type: "Mensal",
      month: 75,
      value: 10441.23004136673,
      indexType: "CUB",
      indexValue: "1",
      initialMonth: 1,
      isDownPayment: false,
      originalValue: 5000,
      isInstallmentPlan: true,
      isConstructionInterest: false,
    },
    {
      type: "Mensal",
      month: 76,
      value: 10545.64234178039,
      indexType: "CUB",
      indexValue: "1",
      initialMonth: 1,
      isDownPayment: false,
      originalValue: 5000,
      isInstallmentPlan: true,
      isConstructionInterest: false,
    },
    {
      type: "Mensal",
      month: 77,
      value: 10651.0987651982,
      indexType: "CUB",
      indexValue: "1",
      initialMonth: 1,
      isDownPayment: false,
      originalValue: 5000,
      isInstallmentPlan: true,
      isConstructionInterest: false,
    },
    {
      type: "Mensal",
      month: 78,
      value: 10757.60975285018,
      indexType: "CUB",
      indexValue: "1",
      initialMonth: 1,
      isDownPayment: false,
      originalValue: 5000,
      isInstallmentPlan: true,
      isConstructionInterest: false,
    },
    {
      type: "Mensal",
      month: 79,
      value: 10865.18585037868,
      indexType: "CUB",
      indexValue: "1",
      initialMonth: 1,
      isDownPayment: false,
      originalValue: 5000,
      isInstallmentPlan: true,
      isConstructionInterest: false,
    },
    {
      type: "Mensal",
      month: 80,
      value: 10973.83770888247,
      indexType: "CUB",
      indexValue: "1",
      initialMonth: 1,
      isDownPayment: false,
      originalValue: 5000,
      isInstallmentPlan: true,
      isConstructionInterest: false,
    },
    {
      type: "Mensal",
      month: 81,
      value: 11083.57608597129,
      indexType: "CUB",
      indexValue: "1",
      initialMonth: 1,
      isDownPayment: false,
      originalValue: 5000,
      isInstallmentPlan: true,
      isConstructionInterest: false,
    },
    {
      type: "Mensal",
      month: 82,
      value: 11194.411846831,
      indexType: "CUB",
      indexValue: "1",
      initialMonth: 1,
      isDownPayment: false,
      originalValue: 5000,
      isInstallmentPlan: true,
      isConstructionInterest: false,
    },
    {
      type: "Mensal",
      month: 83,
      value: 11306.35596529932,
      indexType: "CUB",
      indexValue: "1",
      initialMonth: 1,
      isDownPayment: false,
      originalValue: 5000,
      isInstallmentPlan: true,
      isConstructionInterest: false,
    },
    {
      type: "Mensal",
      month: 84,
      value: 11419.41952495231,
      indexType: "CUB",
      indexValue: "1",
      initialMonth: 1,
      isDownPayment: false,
      originalValue: 5000,
      isInstallmentPlan: true,
      isConstructionInterest: false,
    },
    {
      type: "Mensal",
      month: 85,
      value: 11533.61372020183,
      indexType: "CUB",
      indexValue: "1",
      initialMonth: 1,
      isDownPayment: false,
      originalValue: 5000,
      isInstallmentPlan: true,
      isConstructionInterest: false,
    },
    {
      type: "Mensal",
      month: 86,
      value: 11648.94985740385,
      indexType: "CUB",
      indexValue: "1",
      initialMonth: 1,
      isDownPayment: false,
      originalValue: 5000,
      isInstallmentPlan: true,
      isConstructionInterest: false,
    },
    {
      type: "Mensal",
      month: 87,
      value: 11765.43935597789,
      indexType: "CUB",
      indexValue: "1",
      initialMonth: 1,
      isDownPayment: false,
      originalValue: 5000,
      isInstallmentPlan: true,
      isConstructionInterest: false,
    },
    {
      type: "Mensal",
      month: 88,
      value: 11883.09374953767,
      indexType: "CUB",
      indexValue: "1",
      initialMonth: 1,
      isDownPayment: false,
      originalValue: 5000,
      isInstallmentPlan: true,
      isConstructionInterest: false,
    },
    {
      type: "Mensal",
      month: 89,
      value: 12001.92468703304,
      indexType: "CUB",
      indexValue: "1",
      initialMonth: 1,
      isDownPayment: false,
      originalValue: 5000,
      isInstallmentPlan: true,
      isConstructionInterest: false,
    },
    {
      type: "Mensal",
      month: 90,
      value: 12121.94393390337,
      indexType: "CUB",
      indexValue: "1",
      initialMonth: 1,
      isDownPayment: false,
      originalValue: 5000,
      isInstallmentPlan: true,
      isConstructionInterest: false,
    },
    {
      type: "Mensal",
      month: 91,
      value: 12243.16337324241,
      indexType: "CUB",
      indexValue: "1",
      initialMonth: 1,
      isDownPayment: false,
      originalValue: 5000,
      isInstallmentPlan: true,
      isConstructionInterest: false,
    },
    {
      type: "Mensal",
      month: 92,
      value: 12365.59500697483,
      indexType: "CUB",
      indexValue: "1",
      initialMonth: 1,
      isDownPayment: false,
      originalValue: 5000,
      isInstallmentPlan: true,
      isConstructionInterest: false,
    },
    {
      type: "Mensal",
      month: 93,
      value: 12489.25095704458,
      indexType: "CUB",
      indexValue: "1",
      initialMonth: 1,
      isDownPayment: false,
      originalValue: 5000,
      isInstallmentPlan: true,
      isConstructionInterest: false,
    },
    {
      type: "Mensal",
      month: 94,
      value: 12614.14346661503,
      indexType: "CUB",
      indexValue: "1",
      initialMonth: 1,
      isDownPayment: false,
      originalValue: 5000,
      isInstallmentPlan: true,
      isConstructionInterest: false,
    },
    {
      type: "Mensal",
      month: 95,
      value: 12740.28490128118,
      indexType: "CUB",
      indexValue: "1",
      initialMonth: 1,
      isDownPayment: false,
      originalValue: 5000,
      isInstallmentPlan: true,
      isConstructionInterest: false,
    },
    {
      type: "Mensal",
      month: 96,
      value: 12867.68775029399,
      indexType: "CUB",
      indexValue: "1",
      initialMonth: 1,
      isDownPayment: false,
      originalValue: 5000,
      isInstallmentPlan: true,
      isConstructionInterest: false,
    },
    {
      type: "Mensal",
      month: 97,
      value: 12996.36462779693,
      indexType: "CUB",
      indexValue: "1",
      initialMonth: 1,
      isDownPayment: false,
      originalValue: 5000,
      isInstallmentPlan: true,
      isConstructionInterest: false,
    },
    {
      type: "Mensal",
      month: 98,
      value: 13126.3282740749,
      indexType: "CUB",
      indexValue: "1",
      initialMonth: 1,
      isDownPayment: false,
      originalValue: 5000,
      isInstallmentPlan: true,
      isConstructionInterest: false,
    },
    {
      type: "Mensal",
      month: 99,
      value: 13257.59155681565,
      indexType: "CUB",
      indexValue: "1",
      initialMonth: 1,
      isDownPayment: false,
      originalValue: 5000,
      isInstallmentPlan: true,
      isConstructionInterest: false,
    },
    {
      type: "Mensal",
      month: 100,
      value: 13390.1674723838,
      indexType: "CUB",
      indexValue: "1",
      initialMonth: 1,
      isDownPayment: false,
      originalValue: 5000,
      isInstallmentPlan: true,
      isConstructionInterest: false,
    },
    {
      type: "Anual",
      month: 1,
      value: 25000,
      indexType: "INCC - M",
      indexValue: "1",
      initialMonth: 1,
      isDownPayment: false,
      originalValue: 25000,
      isInstallmentPlan: false,
      isConstructionInterest: false,
    },
    {
      type: "Anual",
      month: 13,
      value: 28170.62575329925,
      indexType: "INCC - M",
      indexValue: "1",
      initialMonth: 1,
      isDownPayment: false,
      originalValue: 25000,
      isInstallmentPlan: false,
      isConstructionInterest: false,
    },
    {
      type: "Anual",
      month: 25,
      value: 31743.36621329786,
      indexType: "INCC - M",
      indexValue: "1",
      initialMonth: 1,
      isDownPayment: false,
      originalValue: 25000,
      isInstallmentPlan: false,
      isConstructionInterest: false,
    },
    {
      type: "Anual",
      month: 37,
      value: 35769.21958978952,
      indexType: "INCC - M",
      indexValue: "1",
      initialMonth: 1,
      isDownPayment: false,
      originalValue: 25000,
      isInstallmentPlan: false,
      isConstructionInterest: false,
    },
    {
      type: "Anual",
      month: 49,
      value: 40305.65194206162,
      indexType: "INCC - M",
      indexValue: "1",
      initialMonth: 1,
      isDownPayment: false,
      originalValue: 25000,
      isInstallmentPlan: false,
      isConstructionInterest: false,
    },
    {
      type: "Anual",
      month: 61,
      value: 45417.41746410227,
      indexType: "INCC - M",
      indexValue: "1",
      initialMonth: 1,
      isDownPayment: false,
      originalValue: 25000,
      isInstallmentPlan: false,
      isConstructionInterest: false,
    },
    {
      type: "Anual",
      month: 73,
      value: 51177.48280250328,
      indexType: "INCC - M",
      indexValue: "1",
      initialMonth: 1,
      isDownPayment: false,
      originalValue: 25000,
      isInstallmentPlan: false,
      isConstructionInterest: false,
    },
    {
      type: "Anual",
      month: 85,
      value: 57668.06860100914,
      indexType: "INCC - M",
      indexValue: "1",
      initialMonth: 1,
      isDownPayment: false,
      originalValue: 25000,
      isInstallmentPlan: false,
      isConstructionInterest: false,
    },
    {
      type: "Entrega das Chaves 28",
      month: 28,
      value: 300000,
      description: "",
      initialMonth: 40,
      isDownPayment: false,
      originalValue: 300000,
      isInstallmentPlan: false,
      isConstructionInterest: false,
    },
  ],
  inCashFees: 0,
  downPayment: 250000,
  initialDate: dayjs().format("MM/YYYY"),
  initialRentMonth: dayjs().add(40, "month").format("MM/YYYY"),
  initialFinancingMonth: dayjs().add(1, "month").format("MM/YYYY"),
  financingFeesDate: dayjs().add(1, "month").format("MM/YYYY"),
  brokerageFee: 0,
  interestRate: 0,
  financingFees: 0,
  financingFeesDescription: "",
  investTheRest: true,
  propertyValue: 1250000,
  PVDiscountRate: 8,
  financingYears: 35,
  financingMonths: 0,
  personalBalance: 0,
  amortizationType: "PRICE",
  initialRentValue: 6000,
  installmentValue: 0,
  annualYieldRate: 12,
  outstandingBalance: null,
  rentAppreciationRate: 12,
  rentMonthlyYieldRate: 0.8,
  considerCapitalGainsTax: false,
  propertyAppreciationRate: 10,
  appraisalValue: undefined,
  financingQuota: undefined,
} as PropertyData;

export default data;
